URL = "https://www.saucedemo.com/"
userNameInput = "user-name"
passwordInput = "password"
loginButton = "login-button"
errorMessage = "//*[@id='login_button_container']/div/form/div[3]/h3"
addCart = "add-to-cart-sauce-labs-backpack"
addCart1 = "add-to-cart-sauce-labs-bike-light"
cartButton = "/html/body/div/div/div/div[1]/div[1]/div[3]/a"
delCart = "remove-sauce-labs-backpack"
delCart1 = "remove-sauce-labs-bike-light"
productList = "inventory_item_name"
inputIcon = "//*[name()='svg']"
errorMessageBtn = "/html/body/div/div/div[2]/div[1]/div/div/form/div[3]/h3/button"
checkoutButton = "checkout"
checkoutURL = f"{URL}checkout-step-one.html"
current_url = f"{URL}inventory.html"
checkoutFirstName = "first-name"
checkoutLastName = "last-name"
checkoutPostalCode ="postal-code"
checkoutErrorMessage ="/html/body/div/div/div/div[2]/div/form/div[1]/div[4]/h3"
checkoutSubmitButton= "continue"
checkoutFirstNameErrorMessage = "Error: First Name is required"
checkoutLastNameErrorMessage = "Error: Last Name is required"
checkoutPostalCodeErrorMessage = "Error: Postal Code is required"
checkoutOverviewURL = f"{URL}checkout-step-two.html"
checkoutFinishButton = "finish"
checkoutCompleteURL = f"{URL}checkout-complete.html"